import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'auth_users',
      columns: [
        { name: 'user_id', type: 'number', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'phone_number', type: 'string', isOptional: true },
        { name: 'image', type: 'string', isOptional: true },
        { name: 'is_super_admin', type: 'boolean' },
        { name: 'email_verified', type: 'boolean' },
        { name: 'phone_verified', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'last_login_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'auth_sessions',
      columns: [
        { name: 'user_id', type: 'number', isIndexed: true },
        { name: 'session_id', type: 'string' },
        { name: 'access_token', type: 'string' },
        { name: 'refresh_token', type: 'string' },
        { name: 'token_type', type: 'string' },
        { name: 'access_expires_at', type: 'number' },
        { name: 'refresh_expires_at', type: 'number' },
        { name: 'absolute_expiry', type: 'number' },
        { name: 'is_active', type: 'boolean' },
        { name: 'mechanism', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'last_used_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'auth_roles',
      columns: [
        { name: 'user_id', type: 'number', isIndexed: true },
        { name: 'store_id', type: 'number', isOptional: true, isIndexed: true },
        { name: 'role_code', type: 'string', isIndexed: true },
        { name: 'role_name', type: 'string' },
        { name: 'permissions', type: 'string' },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'auth_flags',
      columns: [
        { name: 'flag_code', type: 'string', isIndexed: true },
        { name: 'flag_name', type: 'string' },
        { name: 'is_enabled', type: 'boolean' },
        { name: 'value', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'pending_sync',
      columns: [
        { name: 'action', type: 'string' },
        { name: 'endpoint', type: 'string', isIndexed: true },
        { name: 'idempotency_key', type: 'string', isIndexed: true },
        { name: 'payload', type: 'string' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'data_hash', type: 'string', isOptional: true },
        { name: 'retries', type: 'number' },
        { name: 'max_retries', type: 'number' },
        { name: 'next_retry_at', type: 'number', isOptional: true },
        { name: 'last_error_code', type: 'number', isOptional: true },
        { name: 'last_error_message', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'failed_at', type: 'number', isOptional: true },
        { name: 'expires_at', type: 'number', isOptional: true },
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'store_id', type: 'number', isOptional: true, isIndexed: true },
        { name: 'device_id', type: 'string' },
        { name: 'deleted_at', type: 'number', isOptional: true },
        { name: 'sync_attempts', type: 'number' },
      ],
    }),
  ],
});
