import { Module } from '@nestjs/common';
import { LoggerModule as PinoLoggerModule } from 'nestjs-pino';
import { randomUUID } from 'crypto';

@Module({
  imports: [
    PinoLoggerModule.forRootAsync({
      useFactory: () => {
        return {
          pinoHttp: {
            // Automatically capture the correlation ID generated by the RequestIdMiddleware
            genReqId: (req: import('http').IncomingMessage) => {
              return (req.headers['x-request-id'] as string) || randomUUID();
            },
            level: process.env.NODE_ENV !== 'production' ? 'debug' : 'info',
            transport:
              process.env.NODE_ENV !== 'production'
                ? {
                    target: 'pino-pretty',
                    options: {
                      colorize: true,
                      singleLine: true,
                      translateTime: 'SYS:standard',
                      ignore: 'pid,hostname',
                      messageFormat:
                        '{req.method} {req.url} → {res.statusCode} ({responseTime}ms) | {msg}',
                    },
                  }
                : undefined,
          },
        };
      },
    }),
  ],
  exports: [PinoLoggerModule],
})
export class LoggerModule {}
