/**
 * Typed contract between AuthGuard (writer) and SessionRotationInterceptor (reader).
 *
 * AuthGuard stamps this on req.sessionContext after successful validation.
 * SessionRotationInterceptor reads it post-handler and applies the appropriate
 * cookie/DB side effects. Keeping the type here avoids a guard → interceptor
 * import dependency (wrong direction) and makes the contract explicit.
 */
export interface SessionUpdateContext {
  authType: 'cookie';
  sessionToken: string;
  sessionId: number;
  csrfSecretOrToken: string;
  shouldRotateSession: boolean;
  /** Pre-generated by guard for @RotateCsrf() routes; CSRF-only rotation. */
  csrfSecretOverride?: string;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Express {
    interface Request {
      sessionContext?: SessionUpdateContext;
    }
  }
}
