/**
 * Application-wide error code constants.
 *
 * Convention:  <DOMAIN>_<ENTITY>_<REASON>
 *
 * HTTP Hint:
 *  400  – BAD_REQUEST  (validation, malformed input)
 *  401  – UNAUTHORIZED (missing / invalid token)
 *  403  – FORBIDDEN    (authenticated but not allowed)
 *  404  – NOT_FOUND    (resource doesn't exist)
 *  409  – CONFLICT     (duplicate / already exists)
 *  422  – UNPROCESSABLE (business-rule violation)
 *  429  – TOO_MANY_REQUESTS (rate limit)
 *  500  – INTERNAL_ERROR
 */

// ─────────────────────────────────────────────────────────────────────────────
// Generic / Shared
// ─────────────────────────────────────────────────────────────────────────────
export const ErrorCode = {
  // General
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',

  // ─── Auth ───────────────────────────────────────────────────────────────────
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_SESSION_NOT_FOUND: 'AUTH_SESSION_NOT_FOUND',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_PROVIDER_NOT_SUPPORTED: 'AUTH_PROVIDER_NOT_SUPPORTED',
  AUTH_OAUTH_STATE_MISMATCH: 'AUTH_OAUTH_STATE_MISMATCH',
  AUTH_PASSWORD_TOO_WEAK: 'AUTH_PASSWORD_TOO_WEAK',

  // ─── OTP ────────────────────────────────────────────────────────────────────
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ALREADY_USED: 'OTP_ALREADY_USED',
  OTP_MAX_ATTEMPTS_EXCEEDED: 'OTP_MAX_ATTEMPTS_EXCEEDED',
  OTP_SEND_FAILED: 'OTP_SEND_FAILED',

  // ─── User ───────────────────────────────────────────────────────────────────
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  USER_PHONE_ALREADY_EXISTS: 'USER_PHONE_ALREADY_EXISTS',
  USER_PROFILE_INCOMPLETE: 'USER_PROFILE_INCOMPLETE',
  USER_CANNOT_DELETE_SELF: 'USER_CANNOT_DELETE_SELF',
  USER_BLOCKED: 'USER_BLOCKED',
  USER_INACTIVE: 'USER_INACTIVE',
  USER_PASSWORD_MISMATCH: 'USER_PASSWORD_MISMATCH',
  USER_OLD_PASSWORD_INCORRECT: 'USER_OLD_PASSWORD_INCORRECT',

  // ─── Company ────────────────────────────────────────────────────────────────
  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
  COMPANY_ALREADY_EXISTS: 'COMPANY_ALREADY_EXISTS',
  COMPANY_GSTIN_ALREADY_EXISTS: 'COMPANY_GSTIN_ALREADY_EXISTS',
  COMPANY_PAN_ALREADY_EXISTS: 'COMPANY_PAN_ALREADY_EXISTS',
  COMPANY_USER_ALREADY_MEMBER: 'COMPANY_USER_ALREADY_MEMBER',
  COMPANY_USER_NOT_MEMBER: 'COMPANY_USER_NOT_MEMBER',
  COMPANY_OWNER_CANNOT_BE_REMOVED: 'COMPANY_OWNER_CANNOT_BE_REMOVED',
  COMPANY_INACTIVE: 'COMPANY_INACTIVE',

  // ─── RBAC ───────────────────────────────────────────────────────────────────
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_ALREADY_EXISTS: 'ROLE_ALREADY_EXISTS',
  ROLE_IS_SYSTEM: 'ROLE_IS_SYSTEM',
  ROLE_CANNOT_DELETE_SYSTEM: 'ROLE_CANNOT_DELETE_SYSTEM',
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
  PERMISSION_ALREADY_EXISTS: 'PERMISSION_ALREADY_EXISTS',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  ROUTE_ALREADY_EXISTS: 'ROUTE_ALREADY_EXISTS',
  USER_ROLE_MAPPING_NOT_FOUND: 'USER_ROLE_MAPPING_NOT_FOUND',
  USER_ROLE_ALREADY_ASSIGNED: 'USER_ROLE_ALREADY_ASSIGNED',
  ROLE_PERMISSION_NOT_FOUND: 'ROLE_PERMISSION_NOT_FOUND',
  ROLE_PERMISSION_ALREADY_EXISTS: 'ROLE_PERMISSION_ALREADY_EXISTS',

  // ─── Location ───────────────────────────────────────────────────────────────
  COUNTRY_NOT_FOUND: 'COUNTRY_NOT_FOUND',
  COUNTRY_ALREADY_EXISTS: 'COUNTRY_ALREADY_EXISTS',
  STATE_NOT_FOUND: 'STATE_NOT_FOUND',
  STATE_ALREADY_EXISTS: 'STATE_ALREADY_EXISTS',
  CITY_NOT_FOUND: 'CITY_NOT_FOUND',
  CITY_ALREADY_EXISTS: 'CITY_ALREADY_EXISTS',
  ADMIN_DIVISION_NOT_FOUND: 'ADMIN_DIVISION_NOT_FOUND', // Generic for counties, districts, departments, etc.
  POSTAL_CODE_NOT_FOUND: 'POSTAL_CODE_NOT_FOUND',
  POSTAL_CODE_ALREADY_EXISTS: 'POSTAL_CODE_ALREADY_EXISTS',

  // ─── Address ────────────────────────────────────────────────────────────────
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  ADDRESS_TYPE_NOT_FOUND: 'ADDRESS_TYPE_NOT_FOUND',
  ADDRESS_LIMIT_EXCEEDED: 'ADDRESS_LIMIT_EXCEEDED',

  // ─── Communication ──────────────────────────────────────────────────────────
  COMMUNICATION_NOT_FOUND: 'COMMUNICATION_NOT_FOUND',
  COMMUNICATION_TYPE_NOT_FOUND: 'COMMUNICATION_TYPE_NOT_FOUND',
  COMMUNICATION_ALREADY_VERIFIED: 'COMMUNICATION_ALREADY_VERIFIED',

  // ─── Contact Person ─────────────────────────────────────────────────────────
  CONTACT_PERSON_NOT_FOUND: 'CONTACT_PERSON_NOT_FOUND',
  CONTACT_PERSON_TYPE_NOT_FOUND: 'CONTACT_PERSON_TYPE_NOT_FOUND',

  // ─── Notes ──────────────────────────────────────────────────────────────────
  NOTES_NOT_FOUND: 'NOTES_NOT_FOUND',
  NOTES_TYPE_NOT_FOUND: 'NOTES_TYPE_NOT_FOUND',

  // ─── Lookup Registries ──────────────────────────────────────────────────────
  SALUTATION_NOT_FOUND: 'SALUTATION_NOT_FOUND',
  DESIGNATION_NOT_FOUND: 'DESIGNATION_NOT_FOUND',
  STORE_LEGAL_TYPE_NOT_FOUND: 'STORE_LEGAL_TYPE_NOT_FOUND',
  STORE_CATEGORY_NOT_FOUND: 'STORE_CATEGORY_NOT_FOUND',
  CALLING_CODE_NOT_FOUND: 'CALLING_CODE_NOT_FOUND',
  VOLUME_NOT_FOUND: 'VOLUME_NOT_FOUND',
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',

  // ─── File / Upload ──────────────────────────────────────────────────────────
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_SUPPORTED: 'FILE_TYPE_NOT_SUPPORTED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',

  // ─── Tax ────────────────────────────────────────────────────────────────────
  TAX_AGENCY_NOT_FOUND: 'TAX_AGENCY_NOT_FOUND',
  TAX_NAME_NOT_FOUND: 'TAX_NAME_NOT_FOUND',
  TAX_RATE_NOT_FOUND: 'TAX_RATE_NOT_FOUND',
  COMMODITY_CODE_NOT_FOUND: 'COMMODITY_CODE_NOT_FOUND',
  TAX_REGISTRATION_NOT_FOUND: 'TAX_REGISTRATION_NOT_FOUND',
  TAX_REGISTRATION_EXISTS: 'TAX_REGISTRATION_EXISTS',

  // ─── Database ───────────────────────────────────────────────────────────────
  DB_QUERY_FAILED: 'DB_QUERY_FAILED',
  DB_UNIQUE_CONSTRAINT_VIOLATION: 'DB_UNIQUE_CONSTRAINT_VIOLATION',
  DB_FOREIGN_KEY_VIOLATION: 'DB_FOREIGN_KEY_VIOLATION',
  DB_CONNECTION_FAILED: 'DB_CONNECTION_FAILED',
} as const;

/** Convenience type for all valid error code strings. */
export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
